import "dotenv/config";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";
import { db } from "../lib/db";
import { projectSchema, newScene, variantSchema } from "../lib/schema";
import { json } from "../lib/projects";
import { storage, storageKey } from "../lib/storage";
import { command, probe } from "../lib/media";
export async function sampleMedia(dir: string) {
  await mkdir(dir, { recursive: true });
  const width = 960,
    height = 540,
    buffer = Buffer.alloc(width * height * 3);
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 3;
      const hill = y > 340 + Math.sin(x / 140) * 45;
      const sun = (x - 690) ** 2 + (y - 150) ** 2 < 48 ** 2;
      const glow = Math.max(
        0,
        1 - Math.sqrt((x - 690) ** 2 + (y - 150) ** 2) / 400,
      );
      buffer[i] = sun
        ? 250
        : hill
          ? 27
          : Math.round(60 + 120 * (y / height) + 30 * glow);
      buffer[i + 1] = sun
        ? 225
        : hill
          ? 56
          : Math.round(85 + 60 * (y / height) + 20 * glow);
      buffer[i + 2] = sun
        ? 155
        : hill
          ? 43
          : Math.round(102 - (40 * y) / height);
    }
  const ppm = path.join(dir, "original-landscape.ppm");
  await writeFile(
    ppm,
    Buffer.concat([Buffer.from(`P6\n${width} ${height}\n255\n`), buffer]),
  );
  const image = path.join(dir, "original-landscape.png");
  await command(process.env.FFMPEG_PATH || "ffmpeg", [
    "-y",
    "-hide_banner",
    "-loglevel",
    "error",
    "-i",
    ppm,
    "-frames:v",
    "1",
    image,
  ]);
  const audio = path.join(dir, "calibration.wav");
  await command(process.env.FFMPEG_PATH || "ffmpeg", [
    "-y",
    "-hide_banner",
    "-loglevel",
    "error",
    "-f",
    "lavfi",
    "-i",
    "sine=frequency=220:duration=2",
    "-af",
    "volume=0.05,afade=t=in:d=0.2,afade=t=out:st=1.8:d=0.2",
    "-ar",
    "48000",
    "-ac",
    "2",
    audio,
  ]);
  return { image, audio };
}
async function main() {
  const dir = path.resolve("data/sample");
  const media = await sampleMedia(dir);
  const scenes = [
    "Every story starts with a small step.",
    "Keep going, one moment at a time.",
  ].map((n, i) => ({
    ...newScene(i + 1, n),
    duration: 2,
    visual: "Original geometric sunrise illustration",
    motion: i ? ("pan-right" as const) : ("zoom-in" as const),
    transition: i ? ("crossfade" as const) : ("cut" as const),
    overlap: 0.4,
    captions: [
      {
        id: crypto.randomUUID(),
        start: 0,
        end: 2,
        text: n,
        accuracy: "manual" as const,
      },
    ],
  }));
  const doc = projectSchema.parse({
    title: "DEMO · A small beginning",
    topic: "A simple, clearly labeled manual render fixture",
    sources:
      "Original test illustration generated by the sample script. Audio is a quiet calibration tone, not AI narration.",
    script: scenes.map((s) => s.narration).join("\n\n"),
    scenes,
    variants: ["landscape", "vertical"].map((aspect) =>
      variantSchema.parse({
        id: crypto.randomUUID(),
        name: aspect === "landscape" ? "YouTube long" : "Shorts / Reels",
        aspect,
        sceneIds: scenes.map((s) => s.id),
        maxDuration: 180,
      }),
    ),
  });
  const p = await db.project.create({
    data: { title: doc.title, document: json(doc) },
  });
  const ids: string[] = [];
  for (const [file, kind, mime] of [
    [media.image, "image", "image/png"],
    [media.audio, "audio", "audio/wav"],
  ]) {
    const bytes = await readFile(file);
    const key = storageKey(p.id, file.split(".").at(-1)!);
    await storage.put(key, bytes, mime);
    const info = await probe(file);
    const a = await db.asset.create({
      data: {
        projectId: p.id,
        name: path.basename(file),
        kind,
        mime,
        bytes: bytes.length,
        storageKey: key,
        duration: info.duration,
        metadata: json({
          source:
            "Original, generated locally for testing; permitted for reuse",
          probe: info,
        }),
      },
    });
    ids.push(a.id);
  }
  doc.scenes = doc.scenes.map((s) => ({
    ...s,
    assetId: ids[0],
    audioId: ids[1],
    status: "Demo media ready",
  }));
  await db.project.update({
    where: { id: p.id },
    data: { document: json(doc) },
  });
  console.log(
    `Created labeled demo project ${p.id}. Audio is a calibration tone. Upload narration to replace it.`,
  );
  await db.$disconnect();
}
if (process.argv[1]?.endsWith("sample.ts"))
  main().catch((e) => {
    console.error(e.message);
    process.exit(1);
  });
