import 'dotenv/config';
import {readFile,writeFile,access} from 'node:fs/promises';
import {ownerApi} from './youtube-owner';
import {googleRequest} from '../lib/youtube';
import {db} from '../lib/db';
import assert from 'node:assert/strict';
const root='data/productions/divine-wisdom';
async function json(file:string){return JSON.parse((await readFile(file,'utf8')).replace(/^\uFEFF/,''));}
async function exists(file:string){try{await access(file);return true;}catch{return false;}}
async function main(){
 const connection=await ownerApi('status');assert(connection.channelId==='UCZCidygC9i89ye1PEI_nh2Q');
 const uploads=await ownerApi('uploads');
 const done=uploads.filter((u:any)=>u.state==='completed'&&u.videoId);
 const response=await googleRequest(`https://www.googleapis.com/youtube/v3/videos?part=snippet,status,processingDetails&id=${done.map((u:any)=>u.videoId).join(',')}`,{},connection.channelId);
 assert(response.ok,`YouTube verification failed (${response.status})`);
 const live=(await response.json()).items;
 const unreadable=done.filter((u:any)=>!live.some((v:any)=>v.id===u.videoId)).map((u:any)=>({projectId:u.projectId,videoId:u.videoId,title:u.metadata.title,reason:'Not returned by current owner-authorized YouTube videos.list; availability unverified'}));
 const videos=done.filter((u:any)=>live.some((v:any)=>v.id===u.videoId)).map((u:any)=>{const v=live.find((x:any)=>x.id===u.videoId);assert(v.snippet.channelId===connection.channelId);return {projectId:u.projectId,videoId:u.videoId,title:v.snippet.title,privacy:v.status.privacyStatus,publishAt:v.status.publishAt||null,processing:v.processingDetails?.processingStatus,thumbnailApplied:u.thumbnailApplied,url:`https://www.youtube.com/watch?v=${u.videoId}`};});
 const pr=await googleRequest('https://www.googleapis.com/youtube/v3/playlists?part=snippet,status,contentDetails&mine=true&maxResults=50',{},connection.channelId);assert(pr.ok);
 const playlists=(await pr.json()).items.map((p:any)=>({id:p.id,title:p.snippet.title,privacy:p.status.privacyStatus,videos:p.contentDetails.itemCount}));
 const later=[];
 for(let n=15;n<=20;n++){
  const config=await json(`${root}/gita-1-${n}/devotional-v1/episode.json`);
  const jobs=await db.job.findMany({where:{projectId:config.projectId},select:{kind:true,state:true,stage:true}});
  later.push({verse:`1.${n}`,projectId:config.projectId,jobs,finalVerified:await exists(`${root}/gita-1-${n}/devotional-v1/verification-full.json`)});
 }
 const hanuman=await json(`${root}/hanuman-chalisa/state.json`);
 const hanumanJob=await db.job.findUnique({where:{id:hanuman.renderJobs.full},select:{id:true,state:true,stage:true,error:true}});
 const chapter2=await json(`${root}/gita-chapter-2/story-v1/FINAL_DELIVERY.json`),chapter2Video=videos.find((v:any)=>v.projectId===chapter2.projectId);
 const result={checkedAt:new Date().toISOString(),checkedAtIST:new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}),channel:connection.channelTitle,recordedUploadEditions:done.length,unreadable,uploadedEditions:videos.length,uniqueUploadedProductions:new Set(videos.map((v:any)=>v.projectId)).size,processed:videos.filter((v:any)=>v.processing==='succeeded').length,private:videos.filter((v:any)=>v.privacy==='private').length,scheduled:videos.filter((v:any)=>v.publishAt).length,pendingUploads:uploads.filter((u:any)=>u.state!=='completed').map((u:any)=>({id:u.id,state:u.state,stage:u.stage})),videos,playlists,gita15to20:later,chapter2:{...chapter2,youtube:chapter2Video||null},hanuman:{seconds:hanuman.seconds,render:hanumanJob,finalVerified:await exists(`${root}/hanuman-chalisa/verification-full.json`),uploaded:videos.some((v:any)=>v.projectId===hanuman.projectId)}};
 await writeFile(`${root}/COMPLETE_STATUS.json`,JSON.stringify(result,null,2));
 const md=`# Divine Wisdom production status\n\nChecked ${result.checkedAtIST} IST (${result.checkedAt}). Actual YouTube API verification and current app job records.\n\n${result.recordedUploadEditions} historical completed upload records; ${unreadable.length} IDs not returned by YouTube and currently unverified. ${result.uploadedEditions} live-confirmed uploaded editions across ${result.uniqueUploadedProductions} unique productions; ${result.processed} processing succeeded; ${result.private} currently private; ${result.scheduled} have a scheduled public release. The older and corrected Chapter 1 uploads count as two editions of one production.\n\n| Production | Completed | Status |\n| --- | ---: | --- |\n| Bhagavad Gita verse episodes, Chapter 1 Shlokas 1–14 | 14 | Uploaded; live privacy/processing recorded in JSON |\n| Bhagavad Gita series introduction | 1 | Uploaded |\n| Full Chapter 1, corrected | 1 | All 47 meanings preserved; 37:26 Full HD verified; uploaded at https://www.youtube.com/watch?v=5EmRG3uVNTo |\n| Devi Navaratri introduction + nine days | 10 | Locally completed; historical uploads recorded, current YouTube availability unverified |\n| Gita Shlokas 15–20 | ${later.filter(v=>v.finalVerified).length} verified finals | ${later.every(v=>v.finalVerified)?'All six full files decoded; narration complete; no YouTube upload attempted':'Rendering in progress; current jobs recorded in JSON'} |\n| Hanuman Chalisa | ${result.hanuman.finalVerified?1:0} verified finals | Full render job ${hanumanJob?.state}; final quality verification ${result.hanuman.finalVerified?'present':'pending'}; not uploaded |\n\n## Pending\n\n- Separate Gita full-chapter YouTube playlist: prepared locally, not present in live YouTube playlist results. Browser changes blocked by an open Chrome extension panel. Individual-shloka playlist remains intact.\n- Gita Shlokas 15–20: finish authorized narration and rendering; no final verified exports presently.\n- Hanuman Chalisa: complete audio-level and full-file playback checks plus listening review; do not label the existing draft final. Uses a selected recording; a new complete original sung recording was not generated.\n- Complete Chapters 2–18: not produced.\n- Navaratri scheduling: unavailable IDs prevent current verification. ${result.scheduled} scheduled releases among live-confirmed videos only. Local cleanup authorization remains unexecuted; no Navaratri project/media deletion performed.\n- Unused Docker build cache (45.51 GB) and three abandoned render directories removed. New render temporary files and checkpoints now use D: via compose.render-d.yaml; existing projects and media are preserved. Administrator compaction was not retried.\n\n## Uploaded editions\n\n${videos.map((v:any)=>`- [${v.title}](${v.url}) — ${v.privacy}; processing ${v.processing}${v.publishAt?`; release ${v.publishAt}`:''}`).join('\n')}\n`;
 const finalMd=md.replace('| Devi Navaratri introduction + nine days',`| Full Chapter 2, Sankhya Yoga | 1 | All 72 meanings preserved; 42:09 Full HD verified; ${chapter2Video?`uploaded Private at ${chapter2Video.url}; processing ${chapter2Video.processing}`:'YouTube upload pending'} |\n| Devi Navaratri introduction + nine days`).replace('Complete Chapters 2–18: not produced.','Complete Chapters 3–18: not produced.');
 await writeFile(`${root}/COMPLETE_STATUS.md`,finalMd);
 console.log(JSON.stringify({checkedAtIST:result.checkedAtIST,recordedUploadEditions:result.recordedUploadEditions,unreadable:unreadable.map((v:any)=>v.videoId),uploadedEditions:result.uploadedEditions,uniqueUploadedProductions:result.uniqueUploadedProductions,processed:result.processed,private:result.private,scheduled:result.scheduled,pendingUploads:result.pendingUploads,playlists,later:later.map(v=>({verse:v.verse,jobs:v.jobs,finalVerified:v.finalVerified})),hanuman:result.hanuman},null,2));
}
main().catch(e=>{console.error(e.message);process.exitCode=1}).finally(()=>db.$disconnect());
